enum ContractMode { partner, scanner, shared }
class FinalApiEndpoint {
  const FinalApiEndpoint({required this.apiId, required this.mode, required this.method, required this.path, required this.auth, required this.principal, required this.appCode, required this.permissions, required this.attestation, required this.deviceSignature, required this.idempotencyRequired, required this.requestSchema, required this.responseSchema});
  final String apiId;
  final ContractMode mode;
  final String method;
  final String path;
  final bool auth;
  final String? principal;
  final String? appCode;
  final List<String> permissions;
  final String attestation;
  final String deviceSignature;
  final bool idempotencyRequired;
  final String requestSchema;
  final String responseSchema;
}
abstract final class FinalPartnerScannerApiInventory {
  static const endpoints = <FinalApiEndpoint>[
    FinalApiEndpoint(apiId: 'api.0540', mode: ContractMode.partner, method: 'POST', path: '/api/v1/auth/partner/login', auth: false, principal: null, appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'PartnerLoginRequest', responseSchema: 'AuthTokenPairResponse'),
    FinalApiEndpoint(apiId: 'api.0541', mode: ContractMode.partner, method: 'POST', path: '/api/v1/auth/partner/refresh', auth: false, principal: null, appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'RefreshTokenRequest', responseSchema: 'AuthTokenPairResponse'),
    FinalApiEndpoint(apiId: 'api.0542', mode: ContractMode.partner, method: 'POST', path: '/api/v1/auth/partner/logout', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'EmptyBody', responseSchema: 'LogoutResponse'),
    FinalApiEndpoint(apiId: 'api.0543', mode: ContractMode.partner, method: 'POST', path: '/api/v1/auth/partner/logout-all', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'EmptyBody', responseSchema: 'LogoutAllResponse'),
    FinalApiEndpoint(apiId: 'api.0544', mode: ContractMode.partner, method: 'GET', path: '/api/v1/auth/partner/sessions', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'SessionListResponse'),
    FinalApiEndpoint(apiId: 'api.0545', mode: ContractMode.partner, method: 'DELETE', path: '/api/v1/auth/partner/sessions/{session_public_id}', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'RevokeSessionResponse'),
    FinalApiEndpoint(apiId: 'api.partner_app_attestation.challenge', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/app-attestation/challenges', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppAttestationChallengeRequest', responseSchema: 'AppAttestationChallengeResponse'),
    FinalApiEndpoint(apiId: 'api.partner_app_attestation.google.verify', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/app-attestation/google/verify', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'GoogleAttestationVerifyRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.partner_app_attestation.apple.register', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/app-attestation/apple/register', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppleAttestationRegisterRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.partner_app_attestation.apple.assert', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/app-attestation/apple/assert', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppleAttestationAssertRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.partner_device_request_keys.store', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/device-request-keys', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'app.attested:sensitive', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'DeviceRequestKeyStoreRequest', responseSchema: 'DeviceRequestKeyStoreResponse'),
    FinalApiEndpoint(apiId: 'api.partner_device_request_keys.revoke', mode: ContractMode.partner, method: 'DELETE', path: '/api/v1/partner/device-request-keys/{key_public_id}', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>[], attestation: 'none', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'DeviceRequestKeyRevokeResponse'),
    FinalApiEndpoint(apiId: 'api.0209', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.read'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'PartnerDetailModel'),
    FinalApiEndpoint(apiId: 'api.0210', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/profile-change-requests', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.profile.request_change'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'PartnerProfileChangeRequestInput', responseSchema: 'PartnerProfileChangeResponse'),
    FinalApiEndpoint(apiId: 'api.0548', mode: ContractMode.partner, method: 'PATCH', path: '/api/v1/partner/me/profile', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.profile.update'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'PartnerProfileUpdateInput', responseSchema: 'PartnerDetailModel'),
    FinalApiEndpoint(apiId: 'api.0549', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/password', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.password.change'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'ChangePasswordInput', responseSchema: 'SuccessEnvelope'),
    FinalApiEndpoint(apiId: 'api.0211', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/branches', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.branches.view'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'BranchListResponse'),
    FinalApiEndpoint(apiId: 'api.0212', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/branches', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.branches.create'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'CreateBranchInput', responseSchema: 'BranchModel'),
    FinalApiEndpoint(apiId: 'api.0213', mode: ContractMode.partner, method: 'PATCH', path: '/api/v1/partner/me/branches/{branch_public_id}', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.branches.update'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'UpdateBranchInput', responseSchema: 'BranchModel'),
    FinalApiEndpoint(apiId: 'api.0214', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/memberships', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.members.view'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'MembershipListResponse'),
    FinalApiEndpoint(apiId: 'api.0215', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/offers', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['offers.manage'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'OfferListResponse'),
    FinalApiEndpoint(apiId: 'api.0216', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/offers', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['offers.create'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'CreateOfferInput', responseSchema: 'OfferModel'),
    FinalApiEndpoint(apiId: 'api.0217', mode: ContractMode.partner, method: 'PATCH', path: '/api/v1/partner/me/offers/{offer_public_id}', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['offers.update'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'UpdateOfferInput', responseSchema: 'OfferModel'),
    FinalApiEndpoint(apiId: 'api.0218', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/offers/{offer_public_id}/activate', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['offers.activate'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'EmptyBody', responseSchema: 'OfferModel'),
    FinalApiEndpoint(apiId: 'api.0219', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/offers/{offer_public_id}/disable', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['offers.disable'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'DisableOfferInput', responseSchema: 'OfferModel'),
    FinalApiEndpoint(apiId: 'api.0550', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/notifications', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'NotificationListResponse'),
    FinalApiEndpoint(apiId: 'api.0551', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/notifications/unread-count', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'UnreadCountResponse'),
    FinalApiEndpoint(apiId: 'api.0552', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/notifications/{notification_public_id}/read', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'EmptyBody', responseSchema: 'SuccessEnvelope'),
    FinalApiEndpoint(apiId: 'api.0553', mode: ContractMode.partner, method: 'POST', path: '/api/v1/partner/me/notifications/read-all', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'EmptyBody', responseSchema: 'SuccessEnvelope'),
    FinalApiEndpoint(apiId: 'api.0554', mode: ContractMode.partner, method: 'GET', path: '/api/v1/partner/me/notification-preferences', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'NotificationPreferencesResponse'),
    FinalApiEndpoint(apiId: 'api.0555', mode: ContractMode.partner, method: 'PUT', path: '/api/v1/partner/me/notification-preferences', auth: true, principal: 'partner_employee', appCode: 'partner', permissions: <String>['partner.notifications.self'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'UpdateNotificationPreferencesInput', responseSchema: 'NotificationPreferencesResponse'),
    FinalApiEndpoint(apiId: 'api.0033', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/auth/scanner/login', auth: false, principal: null, appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ScannerLoginRequest', responseSchema: 'AuthTokenPairResponse'),
    FinalApiEndpoint(apiId: 'api.0034', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/auth/scanner/refresh', auth: false, principal: null, appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'RefreshTokenRequest', responseSchema: 'AuthTokenPairResponse'),
    FinalApiEndpoint(apiId: 'api.0035', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/auth/scanner/logout', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'EmptyBody', responseSchema: 'LogoutResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_app_attestation.challenge', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/app-attestation/challenges', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppAttestationChallengeRequest', responseSchema: 'AppAttestationChallengeResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_app_attestation.google.verify', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/app-attestation/google/verify', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'GoogleAttestationVerifyRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_app_attestation.apple.register', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/app-attestation/apple/register', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppleAttestationRegisterRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_app_attestation.apple.assert', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/app-attestation/apple/assert', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'AppleAttestationAssertRequest', responseSchema: 'AppAttestationVerifyResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_device_request_keys.store', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/device-request-keys', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'app.attested:sensitive', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'DeviceRequestKeyStoreRequest', responseSchema: 'DeviceRequestKeyStoreResponse'),
    FinalApiEndpoint(apiId: 'api.scanner_device_request_keys.revoke', mode: ContractMode.scanner, method: 'DELETE', path: '/api/v1/scanner/device-request-keys/{key_public_id}', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>[], attestation: 'none', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'DeviceRequestKeyRevokeResponse'),
    FinalApiEndpoint(apiId: 'api.0191', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/context', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'ScannerContextResponse'),
    FinalApiEndpoint(apiId: 'api.0192', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/branches', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'BranchListResponse'),
    FinalApiEndpoint(apiId: 'api.0193', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/context/branch', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'SelectBranchInput', responseSchema: 'SelectBranchResponse'),
    FinalApiEndpoint(apiId: 'api.0194', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/devices', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ListQueryParams', responseSchema: 'ScannerDeviceListResponse'),
    FinalApiEndpoint(apiId: 'api.0195', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/qr/challenge', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'QrChallengeInput', responseSchema: 'QrChallengeResponse'),
    FinalApiEndpoint(apiId: 'api.0196', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/qr/verify', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: false, requestSchema: 'QrVerifyInput', responseSchema: 'ScanResultModel'),
    FinalApiEndpoint(apiId: 'api.0197', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/scans/{scan_public_id}', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'ScanResultModel'),
    FinalApiEndpoint(apiId: 'api.0198', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/scans/{scan_public_id}/eligible-offers', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['scanner.use'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'EligibleOfferListResponse'),
    FinalApiEndpoint(apiId: 'api.0199', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/redemptions/free', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.execute'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'RedeemFreeInput', responseSchema: 'RedemptionModel'),
    FinalApiEndpoint(apiId: 'api.0200', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/redemptions/points', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.execute'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'RedeemPointsInput', responseSchema: 'RedemptionModel'),
    FinalApiEndpoint(apiId: 'api.0546', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/redemptions/discount', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.execute'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'RedeemDiscountInput', responseSchema: 'RedemptionModel'),
    FinalApiEndpoint(apiId: 'api.0203', mode: ContractMode.scanner, method: 'POST', path: '/api/v1/scanner/redemptions/{redemption_public_id}/reverse', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.reverse'], attestation: 'app.attested:sensitive', deviceSignature: 'device.signed:sensitive', idempotencyRequired: true, requestSchema: 'ReverseRedemptionInput', responseSchema: 'RedemptionModel'),
    FinalApiEndpoint(apiId: 'api.0201', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/redemptions', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.view'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'RedemptionHistoryQueryParams', responseSchema: 'RedemptionListResponse'),
    FinalApiEndpoint(apiId: 'api.0202', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/redemptions/{redemption_public_id}', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.view'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'RedemptionModel'),
    FinalApiEndpoint(apiId: 'api.0204', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/statistics/daily', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.stats'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'ScannerStatisticsModel'),
    FinalApiEndpoint(apiId: 'api.0547', mode: ContractMode.scanner, method: 'GET', path: '/api/v1/scanner/statistics', auth: true, principal: 'partner_employee', appCode: 'scanner', permissions: <String>['redemptions.stats'], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'ScannerStatisticsPeriodQueryParams', responseSchema: 'ScannerStatisticsModel'),
    FinalApiEndpoint(apiId: 'api.0227', mode: ContractMode.shared, method: 'GET', path: '/api/v1/app/config', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'AppConfigResponse'),
    FinalApiEndpoint(apiId: 'api.0228', mode: ContractMode.shared, method: 'GET', path: '/api/v1/taxonomies/languages', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'TaxonomyListResponse'),
    FinalApiEndpoint(apiId: 'api.0229', mode: ContractMode.shared, method: 'GET', path: '/api/v1/taxonomies/provinces', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'TaxonomyListResponse'),
    FinalApiEndpoint(apiId: 'api.0230', mode: ContractMode.shared, method: 'GET', path: '/api/v1/taxonomies/cities', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'TaxonomyListResponse'),
    FinalApiEndpoint(apiId: 'api.0231', mode: ContractMode.shared, method: 'GET', path: '/api/v1/taxonomies/areas', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'TaxonomyListResponse'),
    FinalApiEndpoint(apiId: 'api.0234', mode: ContractMode.shared, method: 'GET', path: '/api/v1/taxonomies/partner-types', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'TaxonomyListResponse'),
    FinalApiEndpoint(apiId: 'api.0455', mode: ContractMode.shared, method: 'GET', path: '/api/v1/public/media/{file_public_id}', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'BinaryStream'),
    FinalApiEndpoint(apiId: 'api.0456', mode: ContractMode.shared, method: 'GET', path: '/api/v1/public/app-links', auth: false, principal: null, appCode: null, permissions: <String>[], attestation: 'none', deviceSignature: 'none', idempotencyRequired: false, requestSchema: 'None', responseSchema: 'AppLinksResponse'),
  ];

  static FinalApiEndpoint byId(String apiId) => endpoints.singleWhere((endpoint) => endpoint.apiId == apiId);
  static int get partnerCount => endpoints.where((e) => e.mode == ContractMode.partner).length;
  static int get scannerCount => endpoints.where((e) => e.mode == ContractMode.scanner).length;
  static int get sharedCount => endpoints.where((e) => e.mode == ContractMode.shared).length;
}
